package com.mztrend.service.crawling.candidate

import com.mztrend.client.dto.YoutubeVideoDetail
import java.time.LocalDateTime
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class YoutubeVideoCandidateExtractorTest {
    private val extractor = YoutubeVideoCandidateExtractor()

    @Test
    fun `extract creates ranked candidates from popular video metadata`() {
        val collectedAt = LocalDateTime.of(2026, 6, 1, 3, 0)

        val candidates =
            extractor.extract(
                videos =
                    listOf(
                        youtubeVideo(
                            videoId = "video-1",
                            title = "아이브 Official MV #아이브",
                            description = "아이브 컴백 무대 https://example.com",
                            tags = listOf("아이브", "IVE", "official"),
                            channelName = "아이브",
                            viewCount = 2_000_000,
                        ),
                        youtubeVideo(
                            videoId = "video-2",
                            title = "마라탕후루 shorts 영상",
                            description = "중독성 있는 챌린지 #마라탕후루 full version",
                            tags = listOf("마라탕후루", "챌린지"),
                            channelName = "트렌드 채널",
                            viewCount = 1_500_000,
                        ),
                    ),
                collectedAt = collectedAt,
                limit = 10,
            )

        val words = candidates.map { it.word }
        assertTrue("아이브" in words)
        assertTrue("마라탕후루" in words)
        assertFalse("official" in words)
        assertFalse("mv" in words)
        assertFalse("shorts" in words)
        assertFalse("영상" in words)

        val ive = candidates.single { it.word == "아이브" }
        assertEquals(TrendCandidateSourceType.YOUTUBE_POPULAR, ive.source)
        assertEquals(collectedAt, ive.collectedAt)
        assertEquals(2_000_000L, ive.totalViewCount)
        assertTrue(ive.evidenceCount > 1)
        assertTrue(ive.rank > 0)
        assertTrue(ive.score > 0)
        assertEquals("video-1", ive.evidenceVideos.single().videoId)
        assertEquals("아이브 Official MV #아이브", ive.evidenceVideos.single().title)
        assertEquals("아이브 컴백 무대 https://example.com", ive.evidenceVideos.single().description)
    }

    @Test
    fun `extract applies limit after score ordering`() {
        val candidates =
            extractor.extract(
                videos =
                    listOf(
                        youtubeVideo(
                            videoId = "video-1",
                            title = "낮은점수",
                            viewCount = 10_000,
                        ),
                        youtubeVideo(
                            videoId = "video-2",
                            title = "높은점수 높은점수",
                            tags = listOf("높은점수"),
                            viewCount = 5_000_000,
                        ),
                    ),
                collectedAt = LocalDateTime.of(2026, 6, 1, 3, 0),
                limit = 1,
            )

        assertEquals(1, candidates.size)
        assertEquals("높은점수", candidates.single().word)
        assertEquals(1, candidates.single().rank)
    }

    @Test
    fun `extract suppresses platform noise while preserving contextual song title`() {
        val candidates =
            extractor.extract(
                videos =
                    listOf(
                        youtubeVideo(
                            videoId = "boynextdoor-mv",
                            title = "BOYNEXTDOOR (보이넥스트도어) 'VIRAL' Official MV",
                            description =
                                """
                                BOYNEXTDOOR [HOME]
                                #BOYNEXTDOOR #보이넥스트도어 #BND
                                #HOME #VIRAL
                                Credits : PRODUCTION RIGEND CREATIVE
                                """.trimIndent(),
                            tags = listOf("HYBE", "HYBE LABELS", "BOYNEXTDOOR", "보이넥스트도어", "BND", "HOME", "VIRAL"),
                            channelName = "HYBE LABELS",
                            viewCount = 4_837_306,
                        ),
                        youtubeVideo(
                            videoId = "boynextdoor-topic",
                            title = "VIRAL",
                            description =
                                """
                                Provided to YouTube by KOZ Entertainment
                                VIRAL · BOYNEXTDOOR
                                Auto-generated by YouTube.
                                """.trimIndent(),
                            tags = listOf("BOYNEXTDOOR", "HOME", "VIRAL"),
                            channelName = "BOYNEXTDOOR - Topic",
                            viewCount = 360_813,
                        ),
                        youtubeVideo(
                            videoId = "shorts-noise",
                            title = "Yaru evlo solldranga pakalama.. #shorts #trending #challenge #funny",
                            description =
                                """
                                Nadipathy Cutie Cows #viral #cow #love #youtube #farm #miniature
                                Subscribe to our YouTube channel.
                                """.trimIndent(),
                            tags = listOf("shorts", "viral", "youtube", "trending", "challenge"),
                            channelName = "NRFM-VLOGS",
                            viewCount = 1_437_262,
                        ),
                    ),
                collectedAt = LocalDateTime.of(2026, 6, 10, 16, 0),
                limit = 10,
            )

        val words = candidates.map { it.word }
        assertTrue("viral" in words)
        assertTrue("보이넥스트도어" in words)
        assertFalse("youtube" in words)
        assertFalse("shorts" in words)
        assertFalse("official" in words)
        assertFalse("challenge" in words)
        assertFalse("trending" in words)
    }

    @Test
    fun `extract keeps content names around punctuation and normalizes spaced number variants`() {
        val candidates =
            extractor.extract(
                videos =
                    listOf(
                        youtubeVideo(
                            videoId = "spider-1",
                            title = "≪스파이더맨4: 브랜드뉴데이≫ 촬영장 유출 떡밥 총정리",
                            description = "#스파이더맨브랜드뉴데이 #스파이더맨 #브랜드뉴데이",
                            tags = listOf("스파이더맨 4", "브랜드뉴데이", "마블"),
                            channelName = "무비띵크_Movie Think",
                            viewCount = 406_020,
                        ),
                        youtubeVideo(
                            videoId = "spider-2",
                            title = "[스파이더맨: 브랜드 뉴 데이] 티저 예고편",
                            tags = listOf("스파이더맨4", "브랜드 뉴 데이", "마블"),
                            channelName = "소니픽쳐스코리아",
                            viewCount = 6_849_532,
                        ),
                    ),
                collectedAt = LocalDateTime.of(2026, 6, 10, 16, 0),
                limit = 10,
            )

        val words = candidates.map { it.word }
        assertTrue("스파이더맨4" in words)
        assertTrue("브랜드뉴데이" in words || "브랜드 뉴 데이" in words)
        assertFalse("예고편" in words)
        assertTrue(candidates.single { it.word == "스파이더맨4" }.evidenceCount > 1)
    }

    @Test
    fun `extract removes protocol-less urls and email fragments`() {
        val candidates =
            extractor.extract(
                videos =
                    listOf(
                        youtubeVideo(
                            videoId = "url-noise",
                            title = "보이넥스트도어 컴백 무대",
                            description =
                                """
                                BND.lnk.to/HOME
                                https://www.youtube.com/@boynextdoor
                                www.youtube.com/@hearts2hearts.official?sub_confirmation=1
                                naver.me/IFIAjKrC
                                cafe.naver.com/dowon4376
                                creators@iambrand.co.kr
                                """.trimIndent(),
                            tags = listOf("보이넥스트도어"),
                            channelName = "BOYNEXTDOOR - Topic",
                            viewCount = 1_000_000,
                        ),
                    ),
                collectedAt = LocalDateTime.of(2026, 6, 10, 16, 0),
                limit = 20,
            )

        val words = candidates.map { it.word }
        assertTrue("보이넥스트도어" in words)
        assertFalse("bnd.lnk.to" in words)
        assertFalse("www.youtube.com" in words)
        assertFalse("naver.me" in words)
        assertFalse("cafe.naver.com" in words)
        assertFalse("creators" in words)
        assertFalse("iambrand.co.kr" in words)
    }

    private fun youtubeVideo(
        videoId: String,
        title: String,
        description: String? = null,
        tags: List<String> = emptyList(),
        channelName: String = "채널",
        viewCount: Long? = null,
    ): YoutubeVideoDetail =
        YoutubeVideoDetail(
            videoId = videoId,
            title = title,
            description = description,
            tags = tags,
            channelId = "channel-$videoId",
            channelName = channelName,
            thumbnailUrl = null,
            viewCount = viewCount,
            publishedAt = LocalDateTime.of(2026, 5, 31, 12, 0),
            durationSeconds = null,
            categoryId = null,
        )

    private fun List<TrendCandidate>.indexOfWord(word: String): Int {
        val index = indexOfFirst { it.word == word }
        assertTrue(index >= 0, "Expected candidate '$word' to exist in ${map { it.word }}")
        return index
    }
}
