package com.mztrend.domain

enum class ExternalApiPurpose {
    GEMINI_CANDIDATE_EXTRACTION,
    GEMINI_KEYWORD_EXPLAIN,
    YOUTUBE_POPULAR_VIDEOS,
    YOUTUBE_VIDEO_SEARCH,
    YOUTUBE_VIDEO_DETAILS,
    YOUTUBE_CHANNEL_DETAILS,
    NAVER_TREND_SCORE,
    WEBHOOK_CALLBACK,
    UNKNOWN,
}
